export const ASSET_TICKER_LIST = [
  {
    assetSymbol: "btc",
    assetName: "Bitcoin",
    assetInfoKey: "XXBT",
    requestTicker: "BTCUSD",
    responseTicker: "XXBTZUSD",
    wsTicker: "BTC/USD",
    color: "#f7931a",
  },
  {
    assetSymbol: "eth",
    assetName: "Ethereum",
    assetInfoKey: "XETH",
    requestTicker: "ETHUSD",
    responseTicker: "XETHZUSD",
    wsTicker: "ETH/USD",
    color: "#91a6fc",
  },
  {
    assetSymbol: "xrp",
    assetName: "XRP",
    assetInfoKey: "XXRP",
    requestTicker: "XRPUSD",
    responseTicker: "XXRPZUSD",
    wsTicker: "XRP/USD",
    color: "#25aae1",
  },
  {
    assetSymbol: "sol",
    assetName: "Solana",
    assetInfoKey: "SOL",
    requestTicker: "SOLUSD",
    responseTicker: "SOLUSD",
    wsTicker: "SOL/USD",
    color: "#9945FF",
  },
  {
    assetSymbol: "doge",
    assetName: "Dogecoin",
    assetInfoKey: "XXDG",
    requestTicker: "DOGEUSD",
    responseTicker: "XDGUSD",
    wsTicker: "DOGE/USD",
    color: "#c2a633",
  },
] as const;
